name: basis_batch
description: basis批量处理工具
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.17.3 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    window_size:
        git:
            url: https://github.com/google/flutter-desktop-embedding.git
            path: plugins/window_size
    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
